name = "FINUFFT"
uuid = "d8beea63-0952-562e-9c6a-8e8ef7364055"
author = "Ludvig af Klinteberg <ludvigak@kth.se>"
version = "3.1.1"

[deps]
finufft_jll = "c41cd5a2-72a3-5203-9076-a500b088fc82"

[compat]
finufft_jll = "2.2.0"
julia = "1.3"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "JET", "LinearAlgebra", "Random"]
